//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:/Project/Unity/Gorge/gorge-chart-studio-project/Packages/cn.starbow.gorge.unity/Runtime/Gorge/GorgeCompiler/GorgeCompiler/src/Gorge.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace GorgeCompiler.AntlrGen {

#pragma warning disable 3021

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GorgeParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IGorgeVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.sourceFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSourceFile([NotNull] GorgeParser.SourceFileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDeclaration([NotNull] GorgeParser.EnumDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.enumConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumConstant([NotNull] GorgeParser.EnumConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDeclaration([NotNull] GorgeParser.ClassDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.usingStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingStatement([NotNull] GorgeParser.UsingStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.namespaceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceStatement([NotNull] GorgeParser.NamespaceStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.interfaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDeclaration([NotNull] GorgeParser.InterfaceDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.genericsDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericsDeclaration([NotNull] GorgeParser.GenericsDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.classModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassModifier([NotNull] GorgeParser.ClassModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.superclass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuperclass([NotNull] GorgeParser.SuperclassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.superInterfaces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuperInterfaces([NotNull] GorgeParser.SuperInterfacesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassBody([NotNull] GorgeParser.ClassBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberDeclaration([NotNull] GorgeParser.MemberDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.constructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructorDeclaration([NotNull] GorgeParser.ConstructorDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.superClassConstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuperClassConstructor([NotNull] GorgeParser.SuperClassConstructorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.constructorModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructorModifier([NotNull] GorgeParser.ConstructorModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodDeclaration([NotNull] GorgeParser.MethodDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.methodModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodModifier([NotNull] GorgeParser.MethodModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterList([NotNull] GorgeParser.ParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] GorgeParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldDeclaration([NotNull] GorgeParser.FieldDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation([NotNull] GorgeParser.AnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.annotationIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationIdentifier([NotNull] GorgeParser.AnnotationIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.annotationParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationParameters([NotNull] GorgeParser.AnnotationParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.genericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericType([NotNull] GorgeParser.GenericTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.annotationParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationParameter([NotNull] GorgeParser.AnnotationParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.metadata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetadata([NotNull] GorgeParser.MetadataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.metadataEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetadataEntry([NotNull] GorgeParser.MetadataEntryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] GorgeParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Assignment</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] GorgeParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ConditionalLevel</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalLevel([NotNull] GorgeParser.ConditionalLevelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Conditional</c>
	/// labeled alternative in <see cref="GorgeParser.conditionalLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional([NotNull] GorgeParser.ConditionalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LoginOrLevel</c>
	/// labeled alternative in <see cref="GorgeParser.conditionalLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoginOrLevel([NotNull] GorgeParser.LoginOrLevelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogicalAndLevel</c>
	/// labeled alternative in <see cref="GorgeParser.logicalOrLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalAndLevel([NotNull] GorgeParser.LogicalAndLevelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogicalOr</c>
	/// labeled alternative in <see cref="GorgeParser.logicalOrLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOr([NotNull] GorgeParser.LogicalOrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EqualityLevel</c>
	/// labeled alternative in <see cref="GorgeParser.logicalAndLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityLevel([NotNull] GorgeParser.EqualityLevelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogicalAnd</c>
	/// labeled alternative in <see cref="GorgeParser.logicalAndLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalAnd([NotNull] GorgeParser.LogicalAndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Equality</c>
	/// labeled alternative in <see cref="GorgeParser.equalityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquality([NotNull] GorgeParser.EqualityContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ComparisonLevel</c>
	/// labeled alternative in <see cref="GorgeParser.equalityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonLevel([NotNull] GorgeParser.ComparisonLevelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Inequality</c>
	/// labeled alternative in <see cref="GorgeParser.equalityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInequality([NotNull] GorgeParser.InequalityContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GreaterEqual</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGreaterEqual([NotNull] GorgeParser.GreaterEqualContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LessEqual</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLessEqual([NotNull] GorgeParser.LessEqualContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Greater</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGreater([NotNull] GorgeParser.GreaterContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AdditionLevel</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditionLevel([NotNull] GorgeParser.AdditionLevelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Less</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLess([NotNull] GorgeParser.LessContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Addition</c>
	/// labeled alternative in <see cref="GorgeParser.additionLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddition([NotNull] GorgeParser.AdditionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Subtraction</c>
	/// labeled alternative in <see cref="GorgeParser.additionLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubtraction([NotNull] GorgeParser.SubtractionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MultiplicationLevel</c>
	/// labeled alternative in <see cref="GorgeParser.additionLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicationLevel([NotNull] GorgeParser.MultiplicationLevelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryRightAssociativityLevel</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryRightAssociativityLevel([NotNull] GorgeParser.UnaryRightAssociativityLevelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Multiplication</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplication([NotNull] GorgeParser.MultiplicationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Division</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDivision([NotNull] GorgeParser.DivisionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Remainder</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRemainder([NotNull] GorgeParser.RemainderContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Opposite</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpposite([NotNull] GorgeParser.OppositeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogicalNot</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalNot([NotNull] GorgeParser.LogicalNotContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Cast</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCast([NotNull] GorgeParser.CastContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryLeftAssociativityLevel</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryLeftAssociativityLevel([NotNull] GorgeParser.UnaryLeftAssociativityLevelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeArray</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeArray([NotNull] GorgeParser.TypeArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeGenerics</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeGenerics([NotNull] GorgeParser.TypeGenericsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayAccess</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccess([NotNull] GorgeParser.ArrayAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InjectorLiteral</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInjectorLiteral([NotNull] GorgeParser.InjectorLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MemberAccess</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberAccess([NotNull] GorgeParser.MemberAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayInjectorLiteral</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayInjectorLiteral([NotNull] GorgeParser.ArrayInjectorLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InjectorMemberAccess</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInjectorMemberAccess([NotNull] GorgeParser.InjectorMemberAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeInjector</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeInjector([NotNull] GorgeParser.TypeInjectorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MethodInvocation</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodInvocation([NotNull] GorgeParser.MethodInvocationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PrimaryLevel</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryLevel([NotNull] GorgeParser.PrimaryLevelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LambdaExpression</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaExpression([NotNull] GorgeParser.LambdaExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LiteralExpression</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralExpression([NotNull] GorgeParser.LiteralExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SeparateExpression</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeparateExpression([NotNull] GorgeParser.SeparateExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ConstructorInvocation</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructorInvocation([NotNull] GorgeParser.ConstructorInvocationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayConstructorInvocation</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayConstructorInvocation([NotNull] GorgeParser.ArrayConstructorInvocationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeDelegate</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeDelegate([NotNull] GorgeParser.TypeDelegateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.lambdaExpressionParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaExpressionParameter([NotNull] GorgeParser.LambdaExpressionParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ReferenceAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReferenceAssignmentTarget([NotNull] GorgeParser.ReferenceAssignmentTargetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MemberAccessAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberAccessAssignmentTarget([NotNull] GorgeParser.MemberAccessAssignmentTargetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ThisAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThisAssignmentTarget([NotNull] GorgeParser.ThisAssignmentTargetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayAccessAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccessAssignmentTarget([NotNull] GorgeParser.ArrayAccessAssignmentTargetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InjectorMemberAccessAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInjectorMemberAccessAssignmentTarget([NotNull] GorgeParser.InjectorMemberAccessAssignmentTargetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NonemptyObjectInjector</c>
	/// labeled alternative in <see cref="GorgeParser.objectInjector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonemptyObjectInjector([NotNull] GorgeParser.NonemptyObjectInjectorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EmptyObjectInjector</c>
	/// labeled alternative in <see cref="GorgeParser.objectInjector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyObjectInjector([NotNull] GorgeParser.EmptyObjectInjectorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NonemptyArrayInjector</c>
	/// labeled alternative in <see cref="GorgeParser.arrayInjector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonemptyArrayInjector([NotNull] GorgeParser.NonemptyArrayInjectorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EmptyArrayInjector</c>
	/// labeled alternative in <see cref="GorgeParser.arrayInjector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyArrayInjector([NotNull] GorgeParser.EmptyArrayInjectorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.keyValuePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyValuePair([NotNull] GorgeParser.KeyValuePairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.deletageParameterTypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeletageParameterTypes([NotNull] GorgeParser.DeletageParameterTypesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] GorgeParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LiteralInt</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralInt([NotNull] GorgeParser.LiteralIntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LiteralFloat</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralFloat([NotNull] GorgeParser.LiteralFloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LiteralBool</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralBool([NotNull] GorgeParser.LiteralBoolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LiteralString</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralString([NotNull] GorgeParser.LiteralStringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ThisExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThisExpression([NotNull] GorgeParser.ThisExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NullExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullExpression([NotNull] GorgeParser.NullExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DefaultExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefaultExpression([NotNull] GorgeParser.DefaultExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ReferenceExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReferenceExpression([NotNull] GorgeParser.ReferenceExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InjectorReferenceExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInjectorReferenceExpression([NotNull] GorgeParser.InjectorReferenceExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeInt</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeInt([NotNull] GorgeParser.TypeIntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeFloat</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeFloat([NotNull] GorgeParser.TypeFloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeBool</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeBool([NotNull] GorgeParser.TypeBoolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeString</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeString([NotNull] GorgeParser.TypeStringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeBaseObject</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeBaseObject([NotNull] GorgeParser.TypeBaseObjectContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeAuto</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeAuto([NotNull] GorgeParser.TypeAutoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeVoid</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeVoid([NotNull] GorgeParser.TypeVoidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.codeBlockList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodeBlockList([NotNull] GorgeParser.CodeBlockListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NormalBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNormalBlock([NotNull] GorgeParser.NormalBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfBlock([NotNull] GorgeParser.IfBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SwitchBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchBlock([NotNull] GorgeParser.SwitchBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WhileBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileBlock([NotNull] GorgeParser.WhileBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DoWhileBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoWhileBlock([NotNull] GorgeParser.DoWhileBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ForBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForBlock([NotNull] GorgeParser.ForBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.switchCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchCase([NotNull] GorgeParser.SwitchCaseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NormalCase</c>
	/// labeled alternative in <see cref="GorgeParser.switchCaseCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNormalCase([NotNull] GorgeParser.NormalCaseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DefaultCase</c>
	/// labeled alternative in <see cref="GorgeParser.switchCaseCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefaultCase([NotNull] GorgeParser.DefaultCaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.commaStatementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommaStatementList([NotNull] GorgeParser.CommaStatementListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.commaStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommaStatement([NotNull] GorgeParser.CommaStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.semicolonStatementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSemicolonStatementList([NotNull] GorgeParser.SemicolonStatementListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NormalStatement</c>
	/// labeled alternative in <see cref="GorgeParser.semicolonStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNormalStatement([NotNull] GorgeParser.NormalStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BlockListStatement</c>
	/// labeled alternative in <see cref="GorgeParser.semicolonStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockListStatement([NotNull] GorgeParser.BlockListStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EmptyStatement</c>
	/// labeled alternative in <see cref="GorgeParser.semicolonStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyStatement([NotNull] GorgeParser.EmptyStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LocalVariableDeclarationStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalVariableDeclarationStatement([NotNull] GorgeParser.LocalVariableDeclarationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExpressionStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] GorgeParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ReturnStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] GorgeParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BreakStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] GorgeParser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ContinueStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStatement([NotNull] GorgeParser.ContinueStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LeaveSpecificQuantity</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeaveSpecificQuantity([NotNull] GorgeParser.LeaveSpecificQuantityContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LeaveFor</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeaveFor([NotNull] GorgeParser.LeaveForContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LeaveWhile</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeaveWhile([NotNull] GorgeParser.LeaveWhileContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LeaveSwitch</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeaveSwitch([NotNull] GorgeParser.LeaveSwitchContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LeaveElse</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeaveElse([NotNull] GorgeParser.LeaveElseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LeaveIf</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeaveIf([NotNull] GorgeParser.LeaveIfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LeaveDoWhile</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeaveDoWhile([NotNull] GorgeParser.LeaveDoWhileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GorgeParser.localVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalVariableDeclaration([NotNull] GorgeParser.LocalVariableDeclarationContext context);
}
} // namespace GorgeCompiler.AntlrGen
