//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:/Project/Unity/Gorge/gorge-chart-studio-project/Packages/cn.starbow.gorge.unity/Runtime/Gorge/GorgeCompiler/GorgeCompiler/src/Gorge.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace GorgeCompiler.AntlrGen {

#pragma warning disable 3021


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGorgeListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class GorgeBaseListener : IGorgeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.sourceFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSourceFile([NotNull] GorgeParser.SourceFileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.sourceFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSourceFile([NotNull] GorgeParser.SourceFileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.enumDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDeclaration([NotNull] GorgeParser.EnumDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.enumDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDeclaration([NotNull] GorgeParser.EnumDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.enumConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumConstant([NotNull] GorgeParser.EnumConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.enumConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumConstant([NotNull] GorgeParser.EnumConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDeclaration([NotNull] GorgeParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDeclaration([NotNull] GorgeParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.usingStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsingStatement([NotNull] GorgeParser.UsingStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.usingStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsingStatement([NotNull] GorgeParser.UsingStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.namespaceStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceStatement([NotNull] GorgeParser.NamespaceStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.namespaceStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceStatement([NotNull] GorgeParser.NamespaceStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.interfaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceDeclaration([NotNull] GorgeParser.InterfaceDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.interfaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceDeclaration([NotNull] GorgeParser.InterfaceDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.genericsDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericsDeclaration([NotNull] GorgeParser.GenericsDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.genericsDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericsDeclaration([NotNull] GorgeParser.GenericsDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.classModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassModifier([NotNull] GorgeParser.ClassModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.classModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassModifier([NotNull] GorgeParser.ClassModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.superclass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSuperclass([NotNull] GorgeParser.SuperclassContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.superclass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSuperclass([NotNull] GorgeParser.SuperclassContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.superInterfaces"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSuperInterfaces([NotNull] GorgeParser.SuperInterfacesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.superInterfaces"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSuperInterfaces([NotNull] GorgeParser.SuperInterfacesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBody([NotNull] GorgeParser.ClassBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBody([NotNull] GorgeParser.ClassBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.memberDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberDeclaration([NotNull] GorgeParser.MemberDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.memberDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberDeclaration([NotNull] GorgeParser.MemberDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.constructorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructorDeclaration([NotNull] GorgeParser.ConstructorDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.constructorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructorDeclaration([NotNull] GorgeParser.ConstructorDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.superClassConstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSuperClassConstructor([NotNull] GorgeParser.SuperClassConstructorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.superClassConstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSuperClassConstructor([NotNull] GorgeParser.SuperClassConstructorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.constructorModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructorModifier([NotNull] GorgeParser.ConstructorModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.constructorModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructorModifier([NotNull] GorgeParser.ConstructorModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.methodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodDeclaration([NotNull] GorgeParser.MethodDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.methodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodDeclaration([NotNull] GorgeParser.MethodDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.methodModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodModifier([NotNull] GorgeParser.MethodModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.methodModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodModifier([NotNull] GorgeParser.MethodModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] GorgeParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] GorgeParser.ParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] GorgeParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] GorgeParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.fieldDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldDeclaration([NotNull] GorgeParser.FieldDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.fieldDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldDeclaration([NotNull] GorgeParser.FieldDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotation([NotNull] GorgeParser.AnnotationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotation([NotNull] GorgeParser.AnnotationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.annotationIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationIdentifier([NotNull] GorgeParser.AnnotationIdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.annotationIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationIdentifier([NotNull] GorgeParser.AnnotationIdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.annotationParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationParameters([NotNull] GorgeParser.AnnotationParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.annotationParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationParameters([NotNull] GorgeParser.AnnotationParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.genericType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericType([NotNull] GorgeParser.GenericTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.genericType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericType([NotNull] GorgeParser.GenericTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.annotationParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationParameter([NotNull] GorgeParser.AnnotationParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.annotationParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationParameter([NotNull] GorgeParser.AnnotationParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.metadata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMetadata([NotNull] GorgeParser.MetadataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.metadata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMetadata([NotNull] GorgeParser.MetadataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.metadataEntry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMetadataEntry([NotNull] GorgeParser.MetadataEntryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.metadataEntry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMetadataEntry([NotNull] GorgeParser.MetadataEntryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] GorgeParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] GorgeParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Assignment</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] GorgeParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Assignment</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] GorgeParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ConditionalLevel</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalLevel([NotNull] GorgeParser.ConditionalLevelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ConditionalLevel</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalLevel([NotNull] GorgeParser.ConditionalLevelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Conditional</c>
	/// labeled alternative in <see cref="GorgeParser.conditionalLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional([NotNull] GorgeParser.ConditionalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Conditional</c>
	/// labeled alternative in <see cref="GorgeParser.conditionalLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional([NotNull] GorgeParser.ConditionalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LoginOrLevel</c>
	/// labeled alternative in <see cref="GorgeParser.conditionalLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoginOrLevel([NotNull] GorgeParser.LoginOrLevelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LoginOrLevel</c>
	/// labeled alternative in <see cref="GorgeParser.conditionalLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoginOrLevel([NotNull] GorgeParser.LoginOrLevelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalAndLevel</c>
	/// labeled alternative in <see cref="GorgeParser.logicalOrLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalAndLevel([NotNull] GorgeParser.LogicalAndLevelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalAndLevel</c>
	/// labeled alternative in <see cref="GorgeParser.logicalOrLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalAndLevel([NotNull] GorgeParser.LogicalAndLevelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalOr</c>
	/// labeled alternative in <see cref="GorgeParser.logicalOrLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalOr([NotNull] GorgeParser.LogicalOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalOr</c>
	/// labeled alternative in <see cref="GorgeParser.logicalOrLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalOr([NotNull] GorgeParser.LogicalOrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EqualityLevel</c>
	/// labeled alternative in <see cref="GorgeParser.logicalAndLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualityLevel([NotNull] GorgeParser.EqualityLevelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EqualityLevel</c>
	/// labeled alternative in <see cref="GorgeParser.logicalAndLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualityLevel([NotNull] GorgeParser.EqualityLevelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalAnd</c>
	/// labeled alternative in <see cref="GorgeParser.logicalAndLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalAnd([NotNull] GorgeParser.LogicalAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalAnd</c>
	/// labeled alternative in <see cref="GorgeParser.logicalAndLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalAnd([NotNull] GorgeParser.LogicalAndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Equality</c>
	/// labeled alternative in <see cref="GorgeParser.equalityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEquality([NotNull] GorgeParser.EqualityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Equality</c>
	/// labeled alternative in <see cref="GorgeParser.equalityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEquality([NotNull] GorgeParser.EqualityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ComparisonLevel</c>
	/// labeled alternative in <see cref="GorgeParser.equalityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparisonLevel([NotNull] GorgeParser.ComparisonLevelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ComparisonLevel</c>
	/// labeled alternative in <see cref="GorgeParser.equalityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparisonLevel([NotNull] GorgeParser.ComparisonLevelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Inequality</c>
	/// labeled alternative in <see cref="GorgeParser.equalityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInequality([NotNull] GorgeParser.InequalityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Inequality</c>
	/// labeled alternative in <see cref="GorgeParser.equalityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInequality([NotNull] GorgeParser.InequalityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>GreaterEqual</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGreaterEqual([NotNull] GorgeParser.GreaterEqualContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>GreaterEqual</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGreaterEqual([NotNull] GorgeParser.GreaterEqualContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LessEqual</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLessEqual([NotNull] GorgeParser.LessEqualContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LessEqual</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLessEqual([NotNull] GorgeParser.LessEqualContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Greater</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGreater([NotNull] GorgeParser.GreaterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Greater</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGreater([NotNull] GorgeParser.GreaterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AdditionLevel</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditionLevel([NotNull] GorgeParser.AdditionLevelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AdditionLevel</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditionLevel([NotNull] GorgeParser.AdditionLevelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Less</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLess([NotNull] GorgeParser.LessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Less</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLess([NotNull] GorgeParser.LessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Addition</c>
	/// labeled alternative in <see cref="GorgeParser.additionLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddition([NotNull] GorgeParser.AdditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Addition</c>
	/// labeled alternative in <see cref="GorgeParser.additionLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddition([NotNull] GorgeParser.AdditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Subtraction</c>
	/// labeled alternative in <see cref="GorgeParser.additionLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubtraction([NotNull] GorgeParser.SubtractionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Subtraction</c>
	/// labeled alternative in <see cref="GorgeParser.additionLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubtraction([NotNull] GorgeParser.SubtractionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MultiplicationLevel</c>
	/// labeled alternative in <see cref="GorgeParser.additionLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicationLevel([NotNull] GorgeParser.MultiplicationLevelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MultiplicationLevel</c>
	/// labeled alternative in <see cref="GorgeParser.additionLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicationLevel([NotNull] GorgeParser.MultiplicationLevelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryRightAssociativityLevel</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryRightAssociativityLevel([NotNull] GorgeParser.UnaryRightAssociativityLevelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryRightAssociativityLevel</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryRightAssociativityLevel([NotNull] GorgeParser.UnaryRightAssociativityLevelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Multiplication</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplication([NotNull] GorgeParser.MultiplicationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Multiplication</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplication([NotNull] GorgeParser.MultiplicationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Division</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDivision([NotNull] GorgeParser.DivisionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Division</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDivision([NotNull] GorgeParser.DivisionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Remainder</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRemainder([NotNull] GorgeParser.RemainderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Remainder</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRemainder([NotNull] GorgeParser.RemainderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Opposite</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpposite([NotNull] GorgeParser.OppositeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Opposite</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpposite([NotNull] GorgeParser.OppositeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalNot</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalNot([NotNull] GorgeParser.LogicalNotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalNot</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalNot([NotNull] GorgeParser.LogicalNotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Cast</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCast([NotNull] GorgeParser.CastContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Cast</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCast([NotNull] GorgeParser.CastContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryLeftAssociativityLevel</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryLeftAssociativityLevel([NotNull] GorgeParser.UnaryLeftAssociativityLevelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryLeftAssociativityLevel</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryLeftAssociativityLevel([NotNull] GorgeParser.UnaryLeftAssociativityLevelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeArray</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeArray([NotNull] GorgeParser.TypeArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeArray</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeArray([NotNull] GorgeParser.TypeArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeGenerics</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeGenerics([NotNull] GorgeParser.TypeGenericsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeGenerics</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeGenerics([NotNull] GorgeParser.TypeGenericsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayAccess</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAccess([NotNull] GorgeParser.ArrayAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayAccess</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAccess([NotNull] GorgeParser.ArrayAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>InjectorLiteral</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInjectorLiteral([NotNull] GorgeParser.InjectorLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>InjectorLiteral</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInjectorLiteral([NotNull] GorgeParser.InjectorLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MemberAccess</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberAccess([NotNull] GorgeParser.MemberAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MemberAccess</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberAccess([NotNull] GorgeParser.MemberAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayInjectorLiteral</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayInjectorLiteral([NotNull] GorgeParser.ArrayInjectorLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayInjectorLiteral</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayInjectorLiteral([NotNull] GorgeParser.ArrayInjectorLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>InjectorMemberAccess</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInjectorMemberAccess([NotNull] GorgeParser.InjectorMemberAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>InjectorMemberAccess</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInjectorMemberAccess([NotNull] GorgeParser.InjectorMemberAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeInjector</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeInjector([NotNull] GorgeParser.TypeInjectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeInjector</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeInjector([NotNull] GorgeParser.TypeInjectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MethodInvocation</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodInvocation([NotNull] GorgeParser.MethodInvocationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MethodInvocation</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodInvocation([NotNull] GorgeParser.MethodInvocationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PrimaryLevel</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryLevel([NotNull] GorgeParser.PrimaryLevelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PrimaryLevel</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryLevel([NotNull] GorgeParser.PrimaryLevelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LambdaExpression</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaExpression([NotNull] GorgeParser.LambdaExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LambdaExpression</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaExpression([NotNull] GorgeParser.LambdaExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LiteralExpression</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralExpression([NotNull] GorgeParser.LiteralExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LiteralExpression</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralExpression([NotNull] GorgeParser.LiteralExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SeparateExpression</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeparateExpression([NotNull] GorgeParser.SeparateExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SeparateExpression</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeparateExpression([NotNull] GorgeParser.SeparateExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ConstructorInvocation</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructorInvocation([NotNull] GorgeParser.ConstructorInvocationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ConstructorInvocation</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructorInvocation([NotNull] GorgeParser.ConstructorInvocationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayConstructorInvocation</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayConstructorInvocation([NotNull] GorgeParser.ArrayConstructorInvocationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayConstructorInvocation</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayConstructorInvocation([NotNull] GorgeParser.ArrayConstructorInvocationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeDelegate</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDelegate([NotNull] GorgeParser.TypeDelegateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeDelegate</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDelegate([NotNull] GorgeParser.TypeDelegateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.lambdaExpressionParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaExpressionParameter([NotNull] GorgeParser.LambdaExpressionParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.lambdaExpressionParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaExpressionParameter([NotNull] GorgeParser.LambdaExpressionParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ReferenceAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReferenceAssignmentTarget([NotNull] GorgeParser.ReferenceAssignmentTargetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ReferenceAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReferenceAssignmentTarget([NotNull] GorgeParser.ReferenceAssignmentTargetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MemberAccessAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberAccessAssignmentTarget([NotNull] GorgeParser.MemberAccessAssignmentTargetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MemberAccessAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberAccessAssignmentTarget([NotNull] GorgeParser.MemberAccessAssignmentTargetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ThisAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThisAssignmentTarget([NotNull] GorgeParser.ThisAssignmentTargetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ThisAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThisAssignmentTarget([NotNull] GorgeParser.ThisAssignmentTargetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayAccessAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAccessAssignmentTarget([NotNull] GorgeParser.ArrayAccessAssignmentTargetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayAccessAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAccessAssignmentTarget([NotNull] GorgeParser.ArrayAccessAssignmentTargetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>InjectorMemberAccessAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInjectorMemberAccessAssignmentTarget([NotNull] GorgeParser.InjectorMemberAccessAssignmentTargetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>InjectorMemberAccessAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInjectorMemberAccessAssignmentTarget([NotNull] GorgeParser.InjectorMemberAccessAssignmentTargetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NonemptyObjectInjector</c>
	/// labeled alternative in <see cref="GorgeParser.objectInjector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonemptyObjectInjector([NotNull] GorgeParser.NonemptyObjectInjectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NonemptyObjectInjector</c>
	/// labeled alternative in <see cref="GorgeParser.objectInjector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonemptyObjectInjector([NotNull] GorgeParser.NonemptyObjectInjectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EmptyObjectInjector</c>
	/// labeled alternative in <see cref="GorgeParser.objectInjector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyObjectInjector([NotNull] GorgeParser.EmptyObjectInjectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EmptyObjectInjector</c>
	/// labeled alternative in <see cref="GorgeParser.objectInjector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyObjectInjector([NotNull] GorgeParser.EmptyObjectInjectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NonemptyArrayInjector</c>
	/// labeled alternative in <see cref="GorgeParser.arrayInjector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonemptyArrayInjector([NotNull] GorgeParser.NonemptyArrayInjectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NonemptyArrayInjector</c>
	/// labeled alternative in <see cref="GorgeParser.arrayInjector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonemptyArrayInjector([NotNull] GorgeParser.NonemptyArrayInjectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EmptyArrayInjector</c>
	/// labeled alternative in <see cref="GorgeParser.arrayInjector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyArrayInjector([NotNull] GorgeParser.EmptyArrayInjectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EmptyArrayInjector</c>
	/// labeled alternative in <see cref="GorgeParser.arrayInjector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyArrayInjector([NotNull] GorgeParser.EmptyArrayInjectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.keyValuePair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyValuePair([NotNull] GorgeParser.KeyValuePairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.keyValuePair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyValuePair([NotNull] GorgeParser.KeyValuePairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.deletageParameterTypes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeletageParameterTypes([NotNull] GorgeParser.DeletageParameterTypesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.deletageParameterTypes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeletageParameterTypes([NotNull] GorgeParser.DeletageParameterTypesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] GorgeParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] GorgeParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LiteralInt</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralInt([NotNull] GorgeParser.LiteralIntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LiteralInt</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralInt([NotNull] GorgeParser.LiteralIntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LiteralFloat</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralFloat([NotNull] GorgeParser.LiteralFloatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LiteralFloat</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralFloat([NotNull] GorgeParser.LiteralFloatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LiteralBool</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralBool([NotNull] GorgeParser.LiteralBoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LiteralBool</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralBool([NotNull] GorgeParser.LiteralBoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LiteralString</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralString([NotNull] GorgeParser.LiteralStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LiteralString</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralString([NotNull] GorgeParser.LiteralStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ThisExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThisExpression([NotNull] GorgeParser.ThisExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ThisExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThisExpression([NotNull] GorgeParser.ThisExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NullExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullExpression([NotNull] GorgeParser.NullExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NullExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullExpression([NotNull] GorgeParser.NullExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DefaultExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultExpression([NotNull] GorgeParser.DefaultExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DefaultExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultExpression([NotNull] GorgeParser.DefaultExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ReferenceExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReferenceExpression([NotNull] GorgeParser.ReferenceExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ReferenceExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReferenceExpression([NotNull] GorgeParser.ReferenceExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>InjectorReferenceExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInjectorReferenceExpression([NotNull] GorgeParser.InjectorReferenceExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>InjectorReferenceExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInjectorReferenceExpression([NotNull] GorgeParser.InjectorReferenceExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeInt</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeInt([NotNull] GorgeParser.TypeIntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeInt</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeInt([NotNull] GorgeParser.TypeIntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeFloat</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeFloat([NotNull] GorgeParser.TypeFloatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeFloat</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeFloat([NotNull] GorgeParser.TypeFloatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeBool</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeBool([NotNull] GorgeParser.TypeBoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeBool</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeBool([NotNull] GorgeParser.TypeBoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeString</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeString([NotNull] GorgeParser.TypeStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeString</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeString([NotNull] GorgeParser.TypeStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeBaseObject</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeBaseObject([NotNull] GorgeParser.TypeBaseObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeBaseObject</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeBaseObject([NotNull] GorgeParser.TypeBaseObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeAuto</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeAuto([NotNull] GorgeParser.TypeAutoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeAuto</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeAuto([NotNull] GorgeParser.TypeAutoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeVoid</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeVoid([NotNull] GorgeParser.TypeVoidContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeVoid</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeVoid([NotNull] GorgeParser.TypeVoidContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.codeBlockList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodeBlockList([NotNull] GorgeParser.CodeBlockListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.codeBlockList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodeBlockList([NotNull] GorgeParser.CodeBlockListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NormalBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNormalBlock([NotNull] GorgeParser.NormalBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NormalBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNormalBlock([NotNull] GorgeParser.NormalBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IfBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfBlock([NotNull] GorgeParser.IfBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IfBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfBlock([NotNull] GorgeParser.IfBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SwitchBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchBlock([NotNull] GorgeParser.SwitchBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SwitchBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchBlock([NotNull] GorgeParser.SwitchBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>WhileBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileBlock([NotNull] GorgeParser.WhileBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>WhileBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileBlock([NotNull] GorgeParser.WhileBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DoWhileBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoWhileBlock([NotNull] GorgeParser.DoWhileBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DoWhileBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoWhileBlock([NotNull] GorgeParser.DoWhileBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ForBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForBlock([NotNull] GorgeParser.ForBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ForBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForBlock([NotNull] GorgeParser.ForBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.switchCase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchCase([NotNull] GorgeParser.SwitchCaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.switchCase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchCase([NotNull] GorgeParser.SwitchCaseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NormalCase</c>
	/// labeled alternative in <see cref="GorgeParser.switchCaseCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNormalCase([NotNull] GorgeParser.NormalCaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NormalCase</c>
	/// labeled alternative in <see cref="GorgeParser.switchCaseCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNormalCase([NotNull] GorgeParser.NormalCaseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DefaultCase</c>
	/// labeled alternative in <see cref="GorgeParser.switchCaseCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultCase([NotNull] GorgeParser.DefaultCaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DefaultCase</c>
	/// labeled alternative in <see cref="GorgeParser.switchCaseCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultCase([NotNull] GorgeParser.DefaultCaseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.commaStatementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommaStatementList([NotNull] GorgeParser.CommaStatementListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.commaStatementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommaStatementList([NotNull] GorgeParser.CommaStatementListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.commaStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommaStatement([NotNull] GorgeParser.CommaStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.commaStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommaStatement([NotNull] GorgeParser.CommaStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.semicolonStatementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSemicolonStatementList([NotNull] GorgeParser.SemicolonStatementListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.semicolonStatementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSemicolonStatementList([NotNull] GorgeParser.SemicolonStatementListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NormalStatement</c>
	/// labeled alternative in <see cref="GorgeParser.semicolonStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNormalStatement([NotNull] GorgeParser.NormalStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NormalStatement</c>
	/// labeled alternative in <see cref="GorgeParser.semicolonStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNormalStatement([NotNull] GorgeParser.NormalStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BlockListStatement</c>
	/// labeled alternative in <see cref="GorgeParser.semicolonStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockListStatement([NotNull] GorgeParser.BlockListStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BlockListStatement</c>
	/// labeled alternative in <see cref="GorgeParser.semicolonStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockListStatement([NotNull] GorgeParser.BlockListStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EmptyStatement</c>
	/// labeled alternative in <see cref="GorgeParser.semicolonStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyStatement([NotNull] GorgeParser.EmptyStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EmptyStatement</c>
	/// labeled alternative in <see cref="GorgeParser.semicolonStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyStatement([NotNull] GorgeParser.EmptyStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LocalVariableDeclarationStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalVariableDeclarationStatement([NotNull] GorgeParser.LocalVariableDeclarationStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LocalVariableDeclarationStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalVariableDeclarationStatement([NotNull] GorgeParser.LocalVariableDeclarationStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpressionStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionStatement([NotNull] GorgeParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpressionStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionStatement([NotNull] GorgeParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ReturnStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] GorgeParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ReturnStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] GorgeParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BreakStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStatement([NotNull] GorgeParser.BreakStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BreakStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStatement([NotNull] GorgeParser.BreakStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ContinueStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueStatement([NotNull] GorgeParser.ContinueStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ContinueStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueStatement([NotNull] GorgeParser.ContinueStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LeaveSpecificQuantity</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeaveSpecificQuantity([NotNull] GorgeParser.LeaveSpecificQuantityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LeaveSpecificQuantity</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeaveSpecificQuantity([NotNull] GorgeParser.LeaveSpecificQuantityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LeaveFor</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeaveFor([NotNull] GorgeParser.LeaveForContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LeaveFor</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeaveFor([NotNull] GorgeParser.LeaveForContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LeaveWhile</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeaveWhile([NotNull] GorgeParser.LeaveWhileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LeaveWhile</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeaveWhile([NotNull] GorgeParser.LeaveWhileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LeaveSwitch</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeaveSwitch([NotNull] GorgeParser.LeaveSwitchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LeaveSwitch</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeaveSwitch([NotNull] GorgeParser.LeaveSwitchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LeaveElse</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeaveElse([NotNull] GorgeParser.LeaveElseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LeaveElse</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeaveElse([NotNull] GorgeParser.LeaveElseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LeaveIf</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeaveIf([NotNull] GorgeParser.LeaveIfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LeaveIf</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeaveIf([NotNull] GorgeParser.LeaveIfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LeaveDoWhile</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeaveDoWhile([NotNull] GorgeParser.LeaveDoWhileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LeaveDoWhile</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeaveDoWhile([NotNull] GorgeParser.LeaveDoWhileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.localVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalVariableDeclaration([NotNull] GorgeParser.LocalVariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.localVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalVariableDeclaration([NotNull] GorgeParser.LocalVariableDeclarationContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace GorgeCompiler.AntlrGen
