//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:/Project/Unity/Gorge/gorge-chart-studio-project/Packages/cn.starbow.gorge.unity/Runtime/Gorge/GorgeCompiler/GorgeCompiler/src/Gorge.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace GorgeCompiler.AntlrGen {

#pragma warning disable 3021

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GorgeParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IGorgeListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.sourceFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSourceFile([NotNull] GorgeParser.SourceFileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.sourceFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSourceFile([NotNull] GorgeParser.SourceFileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDeclaration([NotNull] GorgeParser.EnumDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDeclaration([NotNull] GorgeParser.EnumDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.enumConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumConstant([NotNull] GorgeParser.EnumConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.enumConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumConstant([NotNull] GorgeParser.EnumConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDeclaration([NotNull] GorgeParser.ClassDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDeclaration([NotNull] GorgeParser.ClassDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.usingStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsingStatement([NotNull] GorgeParser.UsingStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.usingStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsingStatement([NotNull] GorgeParser.UsingStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.namespaceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceStatement([NotNull] GorgeParser.NamespaceStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.namespaceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceStatement([NotNull] GorgeParser.NamespaceStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.interfaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceDeclaration([NotNull] GorgeParser.InterfaceDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.interfaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceDeclaration([NotNull] GorgeParser.InterfaceDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.genericsDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericsDeclaration([NotNull] GorgeParser.GenericsDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.genericsDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericsDeclaration([NotNull] GorgeParser.GenericsDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.classModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassModifier([NotNull] GorgeParser.ClassModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.classModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassModifier([NotNull] GorgeParser.ClassModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.superclass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSuperclass([NotNull] GorgeParser.SuperclassContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.superclass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSuperclass([NotNull] GorgeParser.SuperclassContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.superInterfaces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSuperInterfaces([NotNull] GorgeParser.SuperInterfacesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.superInterfaces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSuperInterfaces([NotNull] GorgeParser.SuperInterfacesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBody([NotNull] GorgeParser.ClassBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBody([NotNull] GorgeParser.ClassBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberDeclaration([NotNull] GorgeParser.MemberDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberDeclaration([NotNull] GorgeParser.MemberDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.constructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructorDeclaration([NotNull] GorgeParser.ConstructorDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.constructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructorDeclaration([NotNull] GorgeParser.ConstructorDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.superClassConstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSuperClassConstructor([NotNull] GorgeParser.SuperClassConstructorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.superClassConstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSuperClassConstructor([NotNull] GorgeParser.SuperClassConstructorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.constructorModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructorModifier([NotNull] GorgeParser.ConstructorModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.constructorModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructorModifier([NotNull] GorgeParser.ConstructorModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodDeclaration([NotNull] GorgeParser.MethodDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodDeclaration([NotNull] GorgeParser.MethodDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.methodModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodModifier([NotNull] GorgeParser.MethodModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.methodModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodModifier([NotNull] GorgeParser.MethodModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] GorgeParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] GorgeParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] GorgeParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] GorgeParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldDeclaration([NotNull] GorgeParser.FieldDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldDeclaration([NotNull] GorgeParser.FieldDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotation([NotNull] GorgeParser.AnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotation([NotNull] GorgeParser.AnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.annotationIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotationIdentifier([NotNull] GorgeParser.AnnotationIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.annotationIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotationIdentifier([NotNull] GorgeParser.AnnotationIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.annotationParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotationParameters([NotNull] GorgeParser.AnnotationParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.annotationParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotationParameters([NotNull] GorgeParser.AnnotationParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.genericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericType([NotNull] GorgeParser.GenericTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.genericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericType([NotNull] GorgeParser.GenericTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.annotationParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotationParameter([NotNull] GorgeParser.AnnotationParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.annotationParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotationParameter([NotNull] GorgeParser.AnnotationParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.metadata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMetadata([NotNull] GorgeParser.MetadataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.metadata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMetadata([NotNull] GorgeParser.MetadataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.metadataEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMetadataEntry([NotNull] GorgeParser.MetadataEntryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.metadataEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMetadataEntry([NotNull] GorgeParser.MetadataEntryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] GorgeParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] GorgeParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Assignment</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] GorgeParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Assignment</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] GorgeParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ConditionalLevel</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalLevel([NotNull] GorgeParser.ConditionalLevelContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ConditionalLevel</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalLevel([NotNull] GorgeParser.ConditionalLevelContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Conditional</c>
	/// labeled alternative in <see cref="GorgeParser.conditionalLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditional([NotNull] GorgeParser.ConditionalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Conditional</c>
	/// labeled alternative in <see cref="GorgeParser.conditionalLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditional([NotNull] GorgeParser.ConditionalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LoginOrLevel</c>
	/// labeled alternative in <see cref="GorgeParser.conditionalLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoginOrLevel([NotNull] GorgeParser.LoginOrLevelContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LoginOrLevel</c>
	/// labeled alternative in <see cref="GorgeParser.conditionalLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoginOrLevel([NotNull] GorgeParser.LoginOrLevelContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalAndLevel</c>
	/// labeled alternative in <see cref="GorgeParser.logicalOrLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndLevel([NotNull] GorgeParser.LogicalAndLevelContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalAndLevel</c>
	/// labeled alternative in <see cref="GorgeParser.logicalOrLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndLevel([NotNull] GorgeParser.LogicalAndLevelContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalOr</c>
	/// labeled alternative in <see cref="GorgeParser.logicalOrLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOr([NotNull] GorgeParser.LogicalOrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalOr</c>
	/// labeled alternative in <see cref="GorgeParser.logicalOrLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOr([NotNull] GorgeParser.LogicalOrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EqualityLevel</c>
	/// labeled alternative in <see cref="GorgeParser.logicalAndLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityLevel([NotNull] GorgeParser.EqualityLevelContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EqualityLevel</c>
	/// labeled alternative in <see cref="GorgeParser.logicalAndLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityLevel([NotNull] GorgeParser.EqualityLevelContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalAnd</c>
	/// labeled alternative in <see cref="GorgeParser.logicalAndLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAnd([NotNull] GorgeParser.LogicalAndContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalAnd</c>
	/// labeled alternative in <see cref="GorgeParser.logicalAndLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAnd([NotNull] GorgeParser.LogicalAndContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Equality</c>
	/// labeled alternative in <see cref="GorgeParser.equalityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEquality([NotNull] GorgeParser.EqualityContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Equality</c>
	/// labeled alternative in <see cref="GorgeParser.equalityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEquality([NotNull] GorgeParser.EqualityContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ComparisonLevel</c>
	/// labeled alternative in <see cref="GorgeParser.equalityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparisonLevel([NotNull] GorgeParser.ComparisonLevelContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ComparisonLevel</c>
	/// labeled alternative in <see cref="GorgeParser.equalityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparisonLevel([NotNull] GorgeParser.ComparisonLevelContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Inequality</c>
	/// labeled alternative in <see cref="GorgeParser.equalityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInequality([NotNull] GorgeParser.InequalityContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Inequality</c>
	/// labeled alternative in <see cref="GorgeParser.equalityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInequality([NotNull] GorgeParser.InequalityContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>GreaterEqual</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGreaterEqual([NotNull] GorgeParser.GreaterEqualContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>GreaterEqual</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGreaterEqual([NotNull] GorgeParser.GreaterEqualContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LessEqual</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLessEqual([NotNull] GorgeParser.LessEqualContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LessEqual</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLessEqual([NotNull] GorgeParser.LessEqualContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Greater</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGreater([NotNull] GorgeParser.GreaterContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Greater</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGreater([NotNull] GorgeParser.GreaterContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AdditionLevel</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditionLevel([NotNull] GorgeParser.AdditionLevelContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AdditionLevel</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditionLevel([NotNull] GorgeParser.AdditionLevelContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Less</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLess([NotNull] GorgeParser.LessContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Less</c>
	/// labeled alternative in <see cref="GorgeParser.comparisonLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLess([NotNull] GorgeParser.LessContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Addition</c>
	/// labeled alternative in <see cref="GorgeParser.additionLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddition([NotNull] GorgeParser.AdditionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Addition</c>
	/// labeled alternative in <see cref="GorgeParser.additionLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddition([NotNull] GorgeParser.AdditionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Subtraction</c>
	/// labeled alternative in <see cref="GorgeParser.additionLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubtraction([NotNull] GorgeParser.SubtractionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Subtraction</c>
	/// labeled alternative in <see cref="GorgeParser.additionLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubtraction([NotNull] GorgeParser.SubtractionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MultiplicationLevel</c>
	/// labeled alternative in <see cref="GorgeParser.additionLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicationLevel([NotNull] GorgeParser.MultiplicationLevelContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MultiplicationLevel</c>
	/// labeled alternative in <see cref="GorgeParser.additionLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicationLevel([NotNull] GorgeParser.MultiplicationLevelContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryRightAssociativityLevel</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryRightAssociativityLevel([NotNull] GorgeParser.UnaryRightAssociativityLevelContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryRightAssociativityLevel</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryRightAssociativityLevel([NotNull] GorgeParser.UnaryRightAssociativityLevelContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Multiplication</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplication([NotNull] GorgeParser.MultiplicationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Multiplication</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplication([NotNull] GorgeParser.MultiplicationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Division</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDivision([NotNull] GorgeParser.DivisionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Division</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDivision([NotNull] GorgeParser.DivisionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Remainder</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRemainder([NotNull] GorgeParser.RemainderContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Remainder</c>
	/// labeled alternative in <see cref="GorgeParser.multiplicationLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRemainder([NotNull] GorgeParser.RemainderContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Opposite</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpposite([NotNull] GorgeParser.OppositeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Opposite</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpposite([NotNull] GorgeParser.OppositeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalNot</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalNot([NotNull] GorgeParser.LogicalNotContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalNot</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalNot([NotNull] GorgeParser.LogicalNotContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Cast</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCast([NotNull] GorgeParser.CastContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Cast</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCast([NotNull] GorgeParser.CastContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryLeftAssociativityLevel</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryLeftAssociativityLevel([NotNull] GorgeParser.UnaryLeftAssociativityLevelContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryLeftAssociativityLevel</c>
	/// labeled alternative in <see cref="GorgeParser.unaryRightAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryLeftAssociativityLevel([NotNull] GorgeParser.UnaryLeftAssociativityLevelContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeArray</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeArray([NotNull] GorgeParser.TypeArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeArray</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeArray([NotNull] GorgeParser.TypeArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeGenerics</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeGenerics([NotNull] GorgeParser.TypeGenericsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeGenerics</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeGenerics([NotNull] GorgeParser.TypeGenericsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayAccess</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayAccess([NotNull] GorgeParser.ArrayAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayAccess</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayAccess([NotNull] GorgeParser.ArrayAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>InjectorLiteral</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInjectorLiteral([NotNull] GorgeParser.InjectorLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>InjectorLiteral</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInjectorLiteral([NotNull] GorgeParser.InjectorLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MemberAccess</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberAccess([NotNull] GorgeParser.MemberAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MemberAccess</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberAccess([NotNull] GorgeParser.MemberAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayInjectorLiteral</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayInjectorLiteral([NotNull] GorgeParser.ArrayInjectorLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayInjectorLiteral</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayInjectorLiteral([NotNull] GorgeParser.ArrayInjectorLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>InjectorMemberAccess</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInjectorMemberAccess([NotNull] GorgeParser.InjectorMemberAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>InjectorMemberAccess</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInjectorMemberAccess([NotNull] GorgeParser.InjectorMemberAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeInjector</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeInjector([NotNull] GorgeParser.TypeInjectorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeInjector</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeInjector([NotNull] GorgeParser.TypeInjectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MethodInvocation</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodInvocation([NotNull] GorgeParser.MethodInvocationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MethodInvocation</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodInvocation([NotNull] GorgeParser.MethodInvocationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PrimaryLevel</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryLevel([NotNull] GorgeParser.PrimaryLevelContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PrimaryLevel</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryLevel([NotNull] GorgeParser.PrimaryLevelContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LambdaExpression</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaExpression([NotNull] GorgeParser.LambdaExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LambdaExpression</c>
	/// labeled alternative in <see cref="GorgeParser.unaryLeftAssociativityLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaExpression([NotNull] GorgeParser.LambdaExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LiteralExpression</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralExpression([NotNull] GorgeParser.LiteralExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LiteralExpression</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralExpression([NotNull] GorgeParser.LiteralExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SeparateExpression</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeparateExpression([NotNull] GorgeParser.SeparateExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SeparateExpression</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeparateExpression([NotNull] GorgeParser.SeparateExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ConstructorInvocation</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructorInvocation([NotNull] GorgeParser.ConstructorInvocationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ConstructorInvocation</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructorInvocation([NotNull] GorgeParser.ConstructorInvocationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayConstructorInvocation</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayConstructorInvocation([NotNull] GorgeParser.ArrayConstructorInvocationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayConstructorInvocation</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayConstructorInvocation([NotNull] GorgeParser.ArrayConstructorInvocationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeDelegate</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDelegate([NotNull] GorgeParser.TypeDelegateContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeDelegate</c>
	/// labeled alternative in <see cref="GorgeParser.primaryLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDelegate([NotNull] GorgeParser.TypeDelegateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.lambdaExpressionParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaExpressionParameter([NotNull] GorgeParser.LambdaExpressionParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.lambdaExpressionParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaExpressionParameter([NotNull] GorgeParser.LambdaExpressionParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ReferenceAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReferenceAssignmentTarget([NotNull] GorgeParser.ReferenceAssignmentTargetContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ReferenceAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReferenceAssignmentTarget([NotNull] GorgeParser.ReferenceAssignmentTargetContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MemberAccessAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberAccessAssignmentTarget([NotNull] GorgeParser.MemberAccessAssignmentTargetContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MemberAccessAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberAccessAssignmentTarget([NotNull] GorgeParser.MemberAccessAssignmentTargetContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ThisAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThisAssignmentTarget([NotNull] GorgeParser.ThisAssignmentTargetContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ThisAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThisAssignmentTarget([NotNull] GorgeParser.ThisAssignmentTargetContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayAccessAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayAccessAssignmentTarget([NotNull] GorgeParser.ArrayAccessAssignmentTargetContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayAccessAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayAccessAssignmentTarget([NotNull] GorgeParser.ArrayAccessAssignmentTargetContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>InjectorMemberAccessAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInjectorMemberAccessAssignmentTarget([NotNull] GorgeParser.InjectorMemberAccessAssignmentTargetContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>InjectorMemberAccessAssignmentTarget</c>
	/// labeled alternative in <see cref="GorgeParser.assignmentTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInjectorMemberAccessAssignmentTarget([NotNull] GorgeParser.InjectorMemberAccessAssignmentTargetContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NonemptyObjectInjector</c>
	/// labeled alternative in <see cref="GorgeParser.objectInjector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNonemptyObjectInjector([NotNull] GorgeParser.NonemptyObjectInjectorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NonemptyObjectInjector</c>
	/// labeled alternative in <see cref="GorgeParser.objectInjector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNonemptyObjectInjector([NotNull] GorgeParser.NonemptyObjectInjectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EmptyObjectInjector</c>
	/// labeled alternative in <see cref="GorgeParser.objectInjector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyObjectInjector([NotNull] GorgeParser.EmptyObjectInjectorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EmptyObjectInjector</c>
	/// labeled alternative in <see cref="GorgeParser.objectInjector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyObjectInjector([NotNull] GorgeParser.EmptyObjectInjectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NonemptyArrayInjector</c>
	/// labeled alternative in <see cref="GorgeParser.arrayInjector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNonemptyArrayInjector([NotNull] GorgeParser.NonemptyArrayInjectorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NonemptyArrayInjector</c>
	/// labeled alternative in <see cref="GorgeParser.arrayInjector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNonemptyArrayInjector([NotNull] GorgeParser.NonemptyArrayInjectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EmptyArrayInjector</c>
	/// labeled alternative in <see cref="GorgeParser.arrayInjector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyArrayInjector([NotNull] GorgeParser.EmptyArrayInjectorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EmptyArrayInjector</c>
	/// labeled alternative in <see cref="GorgeParser.arrayInjector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyArrayInjector([NotNull] GorgeParser.EmptyArrayInjectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.keyValuePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyValuePair([NotNull] GorgeParser.KeyValuePairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.keyValuePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyValuePair([NotNull] GorgeParser.KeyValuePairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.deletageParameterTypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeletageParameterTypes([NotNull] GorgeParser.DeletageParameterTypesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.deletageParameterTypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeletageParameterTypes([NotNull] GorgeParser.DeletageParameterTypesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] GorgeParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] GorgeParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LiteralInt</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralInt([NotNull] GorgeParser.LiteralIntContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LiteralInt</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralInt([NotNull] GorgeParser.LiteralIntContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LiteralFloat</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralFloat([NotNull] GorgeParser.LiteralFloatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LiteralFloat</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralFloat([NotNull] GorgeParser.LiteralFloatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LiteralBool</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralBool([NotNull] GorgeParser.LiteralBoolContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LiteralBool</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralBool([NotNull] GorgeParser.LiteralBoolContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LiteralString</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralString([NotNull] GorgeParser.LiteralStringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LiteralString</c>
	/// labeled alternative in <see cref="GorgeParser.valueLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralString([NotNull] GorgeParser.LiteralStringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ThisExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThisExpression([NotNull] GorgeParser.ThisExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ThisExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThisExpression([NotNull] GorgeParser.ThisExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NullExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullExpression([NotNull] GorgeParser.NullExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NullExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullExpression([NotNull] GorgeParser.NullExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DefaultExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultExpression([NotNull] GorgeParser.DefaultExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DefaultExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultExpression([NotNull] GorgeParser.DefaultExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ReferenceExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReferenceExpression([NotNull] GorgeParser.ReferenceExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ReferenceExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReferenceExpression([NotNull] GorgeParser.ReferenceExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>InjectorReferenceExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInjectorReferenceExpression([NotNull] GorgeParser.InjectorReferenceExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>InjectorReferenceExpression</c>
	/// labeled alternative in <see cref="GorgeParser.referenceLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInjectorReferenceExpression([NotNull] GorgeParser.InjectorReferenceExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeInt</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeInt([NotNull] GorgeParser.TypeIntContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeInt</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeInt([NotNull] GorgeParser.TypeIntContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeFloat</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeFloat([NotNull] GorgeParser.TypeFloatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeFloat</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeFloat([NotNull] GorgeParser.TypeFloatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeBool</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeBool([NotNull] GorgeParser.TypeBoolContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeBool</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeBool([NotNull] GorgeParser.TypeBoolContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeString</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeString([NotNull] GorgeParser.TypeStringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeString</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeString([NotNull] GorgeParser.TypeStringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeBaseObject</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeBaseObject([NotNull] GorgeParser.TypeBaseObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeBaseObject</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeBaseObject([NotNull] GorgeParser.TypeBaseObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeAuto</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeAuto([NotNull] GorgeParser.TypeAutoContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeAuto</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeAuto([NotNull] GorgeParser.TypeAutoContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeVoid</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeVoid([NotNull] GorgeParser.TypeVoidContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeVoid</c>
	/// labeled alternative in <see cref="GorgeParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeVoid([NotNull] GorgeParser.TypeVoidContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.codeBlockList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeBlockList([NotNull] GorgeParser.CodeBlockListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.codeBlockList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeBlockList([NotNull] GorgeParser.CodeBlockListContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NormalBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNormalBlock([NotNull] GorgeParser.NormalBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NormalBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNormalBlock([NotNull] GorgeParser.NormalBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IfBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfBlock([NotNull] GorgeParser.IfBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IfBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfBlock([NotNull] GorgeParser.IfBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SwitchBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchBlock([NotNull] GorgeParser.SwitchBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SwitchBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchBlock([NotNull] GorgeParser.SwitchBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>WhileBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileBlock([NotNull] GorgeParser.WhileBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>WhileBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileBlock([NotNull] GorgeParser.WhileBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DoWhileBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoWhileBlock([NotNull] GorgeParser.DoWhileBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DoWhileBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoWhileBlock([NotNull] GorgeParser.DoWhileBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ForBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForBlock([NotNull] GorgeParser.ForBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ForBlock</c>
	/// labeled alternative in <see cref="GorgeParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForBlock([NotNull] GorgeParser.ForBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.switchCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchCase([NotNull] GorgeParser.SwitchCaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.switchCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchCase([NotNull] GorgeParser.SwitchCaseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NormalCase</c>
	/// labeled alternative in <see cref="GorgeParser.switchCaseCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNormalCase([NotNull] GorgeParser.NormalCaseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NormalCase</c>
	/// labeled alternative in <see cref="GorgeParser.switchCaseCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNormalCase([NotNull] GorgeParser.NormalCaseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DefaultCase</c>
	/// labeled alternative in <see cref="GorgeParser.switchCaseCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultCase([NotNull] GorgeParser.DefaultCaseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DefaultCase</c>
	/// labeled alternative in <see cref="GorgeParser.switchCaseCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultCase([NotNull] GorgeParser.DefaultCaseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.commaStatementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommaStatementList([NotNull] GorgeParser.CommaStatementListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.commaStatementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommaStatementList([NotNull] GorgeParser.CommaStatementListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.commaStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommaStatement([NotNull] GorgeParser.CommaStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.commaStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommaStatement([NotNull] GorgeParser.CommaStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.semicolonStatementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSemicolonStatementList([NotNull] GorgeParser.SemicolonStatementListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.semicolonStatementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSemicolonStatementList([NotNull] GorgeParser.SemicolonStatementListContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NormalStatement</c>
	/// labeled alternative in <see cref="GorgeParser.semicolonStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNormalStatement([NotNull] GorgeParser.NormalStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NormalStatement</c>
	/// labeled alternative in <see cref="GorgeParser.semicolonStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNormalStatement([NotNull] GorgeParser.NormalStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BlockListStatement</c>
	/// labeled alternative in <see cref="GorgeParser.semicolonStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockListStatement([NotNull] GorgeParser.BlockListStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BlockListStatement</c>
	/// labeled alternative in <see cref="GorgeParser.semicolonStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockListStatement([NotNull] GorgeParser.BlockListStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EmptyStatement</c>
	/// labeled alternative in <see cref="GorgeParser.semicolonStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyStatement([NotNull] GorgeParser.EmptyStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EmptyStatement</c>
	/// labeled alternative in <see cref="GorgeParser.semicolonStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyStatement([NotNull] GorgeParser.EmptyStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LocalVariableDeclarationStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalVariableDeclarationStatement([NotNull] GorgeParser.LocalVariableDeclarationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LocalVariableDeclarationStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalVariableDeclarationStatement([NotNull] GorgeParser.LocalVariableDeclarationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpressionStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionStatement([NotNull] GorgeParser.ExpressionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpressionStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionStatement([NotNull] GorgeParser.ExpressionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ReturnStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] GorgeParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ReturnStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] GorgeParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BreakStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakStatement([NotNull] GorgeParser.BreakStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BreakStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakStatement([NotNull] GorgeParser.BreakStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ContinueStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueStatement([NotNull] GorgeParser.ContinueStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ContinueStatement</c>
	/// labeled alternative in <see cref="GorgeParser.statementContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueStatement([NotNull] GorgeParser.ContinueStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LeaveSpecificQuantity</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeaveSpecificQuantity([NotNull] GorgeParser.LeaveSpecificQuantityContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LeaveSpecificQuantity</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeaveSpecificQuantity([NotNull] GorgeParser.LeaveSpecificQuantityContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LeaveFor</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeaveFor([NotNull] GorgeParser.LeaveForContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LeaveFor</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeaveFor([NotNull] GorgeParser.LeaveForContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LeaveWhile</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeaveWhile([NotNull] GorgeParser.LeaveWhileContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LeaveWhile</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeaveWhile([NotNull] GorgeParser.LeaveWhileContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LeaveSwitch</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeaveSwitch([NotNull] GorgeParser.LeaveSwitchContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LeaveSwitch</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeaveSwitch([NotNull] GorgeParser.LeaveSwitchContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LeaveElse</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeaveElse([NotNull] GorgeParser.LeaveElseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LeaveElse</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeaveElse([NotNull] GorgeParser.LeaveElseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LeaveIf</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeaveIf([NotNull] GorgeParser.LeaveIfContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LeaveIf</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeaveIf([NotNull] GorgeParser.LeaveIfContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LeaveDoWhile</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeaveDoWhile([NotNull] GorgeParser.LeaveDoWhileContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LeaveDoWhile</c>
	/// labeled alternative in <see cref="GorgeParser.leaveBlockTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeaveDoWhile([NotNull] GorgeParser.LeaveDoWhileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GorgeParser.localVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalVariableDeclaration([NotNull] GorgeParser.LocalVariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GorgeParser.localVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalVariableDeclaration([NotNull] GorgeParser.LocalVariableDeclarationContext context);
}
} // namespace GorgeCompiler.AntlrGen
